apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-faro-proxy
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana-faro
    app.kubernetes.io/component: observability
spec:
  replicas: ${FARO_REPLICAS:=2}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-faro
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-faro
    spec:
      containers:
        - name: faro-proxy
          image: grafana/faro-proxy:1.1.0
          envFrom:
            - configMapRef:
                name: grafana-faro-config
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
