apiVersion: v1
kind: Service
metadata:
  name: grafana-faro-proxy
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana-faro
spec:
  selector:
    app.kubernetes.io/name: grafana-faro
  ports:
    - name: http
      port: 80
      targetPort: http
