apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-reference
  namespace: flux-system
  labels:
    app.kubernetes.io/name: echo-reference
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: observability
spec:
  interval: 10m0s
  retryInterval: 2m0s
  timeout: 10m0s
  prune: true
  wait: true

  path: ./IaC/kubernetes/apps/observability/echo-reference/app

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: otel-collector
      namespace: flux-system

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings

  decryption:
    provider: sops
    secretRef:
      name: sops-age
