apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: observability-root
  labels:
    app.kubernetes.io/name: observability-root
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: observability
resources:
  - namespaces.yaml
  - kube-prometheus-stack.yaml
  - grafana-mimir.yaml
  - loki.yaml
  - tempo.yaml
  - pyroscope.yaml
  - otel-collector.yaml
  - beyla.yaml
  - grafana-alloy.yaml
  - grafana-faro.yaml
  - grafana-oncall.yaml
  - echo-reference.yaml
  - kiali.yaml
