apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cost-feature-base
  namespace: flux-system
spec:
  interval: 10m
  path: ./IaC/kubernetes/apps/base/cost-feature
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: networking-base
  sourceRef:
    kind: GitRepository
    name: flux-system
