apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  prune: true
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager
      helix.ai/component: cert-manager
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/cert-manager/cert-manager/app
