---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo
spec:
  interval: 1h
  path: ./IaC/kubernetes/apps/base/kube-system/echo-server/app
  postBuild:
    substituteFrom:
      - name: cluster-settings
        namespace: flux-system
        kind: ConfigMap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
