apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
    labels:
        app.kubernetes.io/name: cert-manager-secret
        app.kubernetes.io/part-of: helix-platform
        app.kubernetes.io/managed-by: fluxcd
        helix.ai/component: cert-manager
type: Opaque
stringData:
    #ENC[AES256_GCM,data:eFiWCxb/6OZfap+yY9Ag+7NnOK1JLeI1XxNAbgw84vM74sIvNM3DQL6DUpAvanJN,iv:mnO6dcTCfPUT0CzIvVWWukQdVrmv8Ik2GDl3MCbsr/I=,tag:U6T6fvhChfhR0PZ6cXEjew==,type:comment]
    #ENC[AES256_GCM,data:/kS3lzccZ4qWYmcw+m3EshxDVX70JWh0xiAPl7hlfGuEeyaBMpDdHbwRBhIRVu3RkazwNWCIx+f/+b57gseTA4Q=,iv:p/1zWT3VaE7ZgtKlwNbUNU0hbp7Dkxa0oQyjE7Gzvb8=,tag:XzE41FMOsXtj3HT0OCmaBw==,type:comment]
    api-token: ENC[AES256_GCM,data:yfupa046a7cAuOE9biE9oEZhWOLzf5MoHjrofkYlM+3JKiwELg==,iv:4KTGc7cQleSOIjhqcszfV2vXxyj7TTS06SFsjvZrTdA=,tag:EkZIwpGJLcowlDIiIjUFXw==,type:str]
sops:
    lastmodified: "2025-11-24T20:36:51Z"
    mac: ENC[AES256_GCM,data:4llmQ7xJkOkr6Hx96iOE1wauGV5DQgw42lb7KwU9MI10Adz0bNLw2oR7GnYXGTSx+nyhXB8ctJ8uekcTdDaS+j/e5t18bmFVD2wLa/zeaP3ET16B7eLIzYHkNK2ms+U+UN6nv79E1kQ31j2UY0Ac3igNAAATP2ZngkZzWIeGGIM=,iv:dOkGZv6T1fvwEN302INqnBT7jNzMwsMzKvAVcjkKd8w=,tag:Jz7fViDY85E16a4sTbT/Zw==,type:str]
    pgp:
        - created_at: "2025-11-24T20:36:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMESIdf+OlsjlDkWjsIrUdVsk1FXLFqXlnrKs8zon3swOkK
            9myrRnVaUmkGWIiI/87V3VU5HLuTrr8kV843HlRQpjDTdioKD6Wshz9DcaCcrKIX
            zxkBiM8ijv/JkqmRvIcXPU++InmXjEXqeR5uaSsdQkfUaAEJAhBZE50bFHdITq/1
            2FuAehz4+DRun8WaO9b0JkAGR0rdNnWndcTGty7QXK78cxtzupx2E9hESWYLXJ/m
            44e53jLMz8bwy/IStR80D29XBqNlPUHQh+jzsBKf7m6JIMCcfDODhDaM
            =Pd49
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-24T20:36:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwME9diAbZUsVEP0XFZ9H2tFsmQ0nRVbHrPBzfT3ibTwtZO9
            VmCqrtGKZ6eNAzv6EMDqpBj6e96T+/0Zwro/0wBwsByVXNABnpVqZZB1vJEI3VLR
            S7uF9UDe2MkiIhzXGVVkMKJvI16xbCSPpj0nFcc/TfwsNXdU/3v+UmPs8yKBYssa
            cf0u8J7AcJatPfoo+tq73dRoAQkCEBAyuiFyHyfJSF71kbkDArFgTHvGEJb6kJEH
            ZbB+hyDOif8F2a6aDuUK9Fadi1kgtgKCbGjjTP6N1eOJR4Z43ROqcawcWw/OuH4j
            7RXE4za9t5b03CovidVaFT1hnU/Lfu0lo/o=
            =tZ0z
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
        - created_at: "2025-11-24T20:36:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DN0J0rS4wp7QSAwMELM+UfFP3tInzrocMshmr3/D7N5McaEGhuMi8jeq35NPC
            PaDYf6b6lWqzWbF0v/UrSKclShd9OZmq96pbeH9pD8BAIOw2dL2HBrmi105Jm8W7
            NKGm1a5wSXSRyvPaLCi+MD4/1LrK1dFSSqLJpgqp+A9DAoUayMphNGJ5a3K/08UT
            NRsML38OR9kXya+j0b0iQ9RoAQkCEDU9feIMfLUO2c9RQYqhGQIsPDjFhfnVcm2I
            SRw9ne5aW7zqJCh3OqCkWUVdrCQnxKNEq5j6y+IKalN/Pu8UzQjqnAYD6DaVskrY
            8BTP+4Z0J+cgfr41UzkKurDGRjcALONRthU=
            =eN26
            -----END PGP MESSAGE-----
          fp: 767B1632A4331A3E3828FAA0E490F1F2A2B9BD10
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
