---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sinless-letsencrypt-production
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${ACME_EMAIL_1}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector:
          dnsZones:
            - "${DOMAIN_1}"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sinless-letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${ACME_EMAIL_1}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - "${DOMAIN_1}"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: helix-letsencrypt-production
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${ACME_EMAIL_2}"
    privateKeySecretRef:
      name: letsencrypt-production-helixaibot
    solvers:
      - selector:
          dnsZones:
            - "${DOMAIN_2}"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: helix-letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${ACME_EMAIL_2}"
    privateKeySecretRef:
      name: letsencrypt-staging-helixaibot
    solvers:
      - selector:
          dnsZones:
            - "${DOMAIN_2}"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
