apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helix-ai
  namespace: flux-system
  labels:
    app.kubernetes.io/name: helix-ai
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
spec:
  interval: 10m0s
  timeout: 2m0s
  url: https://github.com/Sinless777/Helix.git
  ref:
    branch: main
