apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server-app
  labels:
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: monitoring
resources:
  - ./helmrelease.yaml
