apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: helix-observability
  app.kubernetes.io/managed-by: fluxcd
resources:
  - ./namespace.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./tempo/ks.yaml
  - ./pyroscope/ks.yaml
  - ./otel-collector/ks.yaml
  - ./beyla/ks.yaml
  - ./jaeger/ks.yaml
