apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
commonLabels:
  app.kubernetes.io/part-of: helix-observability
  app.kubernetes.io/managed-by: fluxcd
resources:
  - ./namespace.yaml
  - ./kube-prometheus-stack
  - ./loki
  - ./tempo
  - ./pyroscope
  - ./otel-collector
  - ./beyla
  - ./jaeger
