apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-team-readonly
  labels:
    app.kubernetes.io/part-of: helix-platform
    helix.ai/team: security-team
    app.kubernetes.io/managed-by: fluxcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: User
    name: tpierce@sinlessgamesllc.com
    apiGroup: rbac.authorization.k8s.io
