---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-${DOMAIN_1}
  namespace: networking
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: helix-platform
    helix.ai/component: networking-tunnel
spec:
  endpoints:
    - dnsName: "external.${DOMAIN_1}"
      recordType: CNAME
      targets:
        - "${CLOUDFLARE_TUNNEL_ID_1}.cfargotunnel.com"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-${DOMAIN_2}
  namespace: networking
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: helix-platform
    helix.ai/component: networking-tunnel
spec:
  endpoints:
    - dnsName: "external.${DOMAIN_2}"
      recordType: CNAME
      targets:
        - "${CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-${DOMAIN_3}
  namespace: networking
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: helix-platform
    helix.ai/component: networking-tunnel
spec:
  endpoints:
    - dnsName: "external.${DOMAIN_3}"
      recordType: CNAME
      targets:
        - "${CLOUDFLARE_TUNNEL_ID_3}.cfargotunnel.com"
