apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/name: flagger
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: progressive-delivery
namespace: mesh
commonLabels:
  app.kubernetes.io/name: flagger
  helix.ai/component: progressive-delivery
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: flagger-values
    files:
      - values.yaml=./configs/values.yaml
    options:
      disableNameSuffixHash: true
generatorOptions:
  disableNameSuffixHash: true
