apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: dr-chaos
  labels:
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-platform
spec:
  interval: 30m
  timeout: 10m
  releaseName: chaos-mesh
  targetNamespace: dr-chaos
  suspend: true
  chart:
    spec:
      chart: chaos-mesh
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: chaos-mesh-values
      valuesKey: values.yaml
