apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
  labels:
    app.kubernetes.io/name: bitnami
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: helm-repository
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
  timeout: 1m
  passCredentials: false
