apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cloudflare
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: helm-repository
spec:
  interval: 1h
  url: https://cloudflare.github.io/helm-charts
  timeout: 1m
  passCredentials: false
