---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

commonLabels:
  app.kubernetes.io/part-of: helix-platform
  app.kubernetes.io/managed-by: fluxcd
  helix.ai/component: helm-repositories

resources:
  - ./helm-repo-cilium.yaml
  - ./helm-repo-bitnami.yaml
  - ./helm-repo-chaos-mesh.yaml
  - ./helm-repo-bjw-s.yaml
  - ./helm-repo-cloudflare.yaml
  - ./helm-repo-coredns.yaml
  - ./helm-repo-crowdsec.yaml
  - ./helm-repo-emissary-ingress.yaml
  - ./helm-repo-external-dns.yaml
  - ./helm-repo-falcosecurity.yaml
  - ./helm-repo-flagger.yaml
  - ./helm-repo-grafana.yaml
  - ./helm-repo-hashicorp.yaml
  - ./helm-repo-homepage.yaml
  - ./helm-repo-istio.yaml
  - ./helm-repo-jaegertracing.yaml
  - ./helm-repo-jetstack.yaml
  - ./helm-repo-kiali.yaml
  - ./helm-repo-kubearmor.yaml
  - ./helm-repo-kubescape.yaml
  - ./helm-repo-metrics-server.yaml
  - ./helm-repo-nats.yaml
  - ./helm-repo-openfeature.yaml
  - ./helm-repo-opencost.yaml
  - ./helm-repo-opentelemetry-helm.yaml
  - ./helm-repo-prometheus-community.yaml
  - ./helm-repo-rook-release.yaml
  - ./helm-repo-vmware-tanzu.yaml
