---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

commonLabels:
  app.kubernetes.io/part-of: helix-platform
  app.kubernetes.io/managed-by: fluxcd
  helix.ai/component: helm-repositories

resources:
  - ./cilium.yaml
  - ./bitnami.yaml
  - ./chaos-mesh.yaml
  - ./bjw-s.yaml
  - ./cloudflare.yaml
  - ./coredns.yaml
  - ./crowdsec.yaml
  - ./emissary-ingress.yaml
  - ./external-dns.yaml
  - ./falcosecurity.yaml
  - ./flagger.yaml
  - ./grafana.yaml
  - ./hashicorp.yaml
  - ./homepage.yaml
  - ./istio.yaml
  - ./jaegertracing.yaml
  - ./jetstack.yaml
  - ./kiali.yaml
  - ./kubearmor.yaml
  - ./kubescape.yaml
  - ./metrics-server.yaml
  - ./nats.yaml
  - ./openfeature.yaml
  - ./opencost.yaml
  - ./opentelemetry-helm.yaml
  - ./prometheus-community.yaml
  - ./rook-release.yaml
  - ./vmware-tanzu.yaml
