apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/helix
patches:
  - path: ./patches/api-deployment-dev.yaml
    target:
      kind: Deployment
      name: helix-api
  - path: ./patches/frontend-deployment-dev.yaml
    target:
      kind: Deployment
      name: helix-frontend
  - path: ./patches/workers-deployment-dev.yaml
    target:
      kind: Deployment
      name: helix-workers
  - path: ./patches/virtualservice-dev.yaml
    target:
      kind: VirtualService
      name: helix
  - path: ./patches/hpa-dev.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: helix
