apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flagger
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: progressive-delivery
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  prune: true
  targetNamespace: mesh
  commonMetadata:
    labels:
      app.kubernetes.io/name: flagger
      helix.ai/component: progressive-delivery
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/mesh/flagger/app
