---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: envoy-external
  namespace: network
  labels:
    app.kubernetes.io/name: envoy-external
    app.kubernetes.io/component: service-mesh
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: service-mesh
spec:
  selector:
    istio: ingressgateway
  servers:
    - name: domain1
      port:
        number: 443
        name: https-domain1
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: envoy-external-domain1-tls
        minProtocolVersion: TLSV1_3
        maxProtocolVersion: TLSV1_3
      hosts:
        - "external.$(DOMAIN_1)"
        - "*.$(DOMAIN_1)"
    - name: domain2
      port:
        number: 443
        name: https-domain2
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: envoy-external-domain2-tls
        minProtocolVersion: TLSV1_3
        maxProtocolVersion: TLSV1_3
      hosts:
        - "external.$(DOMAIN_2)"
        - "*.$(DOMAIN_2)"
    - name: domain3
      port:
        number: 443
        name: https-domain3
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: envoy-external-domain3-tls
        minProtocolVersion: TLSV1_3
        maxProtocolVersion: TLSV1_3
      hosts:
        - "external.$(DOMAIN_3)"
        - "*.$(DOMAIN_3)"
