apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-domain-1
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-production-v02.api.letsencrypt.org/directory
    email: "${ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production-domain-1
    solvers:
      - selector:
          dnsZones:
            - "${DOMAIN_1}"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-domain-2
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-production-v02.api.letsencrypt.org/directory
    email: "${ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production-domain-2
    solvers:
      - selector:
          dnsZones:
            - "${DOMAIN_2}"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-domain-3
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-production-v02.api.letsencrypt.org/directory
    email: "${ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production-domain-3
    solvers:
      - selector:
          dnsZones:
            - "${DOMAIN_3}"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
