apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-domain-1
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${ACME_EMAIL_1}
    privateKeySecretRef:
      name: letsencrypt-staging-domain-1
    solvers:
      - selector:
          dnsZones:
            - ${DOMAIN_1}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-domain-2
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${ACME_EMAIL_2}
    privateKeySecretRef:
      name: letsencrypt-staging-domain-2
    solvers:
      - selector:
          dnsZones:
            - ${DOMAIN_2}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-domain-3
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${ACME_EMAIL_3}
    privateKeySecretRef:
      name: letsencrypt-staging-domain-3
    solvers:
      - selector:
          dnsZones:
            - ${DOMAIN_3}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
