apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: loki-app
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: observability
namespace: observability
resources:
  - helmrelease.yaml
