---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
  namespace: network
spec:
  endpoints:
    - dnsName: "external.${DOMAIN_1}"
      recordType: CNAME
      targets: ["${TUNNEL_ID_1}.cfargotunnel.com"]
    - dnsName: "external.${DOMAIN_2}"
      recordType: CNAME
      targets: ["${TUNNEL_ID_2}.cfargotunnel.com"]
    - dnsName: "external.${DOMAIN_3}"
      recordType: CNAME
      targets: ["${TUNNEL_ID_3}.cfargotunnel.com"]
