apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: network
stringData:
    #ENC[AES256_GCM,data:XzOifZfLSW3LBqXZcIYQ,iv:DzuirpNymavRMCZlvQ5HdE2sVe7GRgjmbKl6jZwiQQY=,tag:rRF0OpaDPqtI5VapGXa85A==,type:comment]
    TUNNEL_ID_1: ENC[AES256_GCM,data:W1PabZA8KnajmR83kTZ5uZlQlVjDB2T1OpWrxh8PIXMY++AG,iv:14KQ7F62uGdCdlIN5P2tI4mE9SS3KeDbuyXNFpUveMQ=,tag:fwCiHKqcSumuFijtebBC0Q==,type:str]
    TUNNEL_TOKEN_1: ENC[AES256_GCM,data:XHpvyMAAhufqxAhoN5ZQTMoli7Dln9DAZo39H+XdypUq3Zpl/GRRtwaNrAnf6W8wx/2eDgmLDSUU5MQN6gJkCqk6cV3qiEQRyOMKyCkl1F3ZO5zAvxBSqopstIZwJv0QooIAIgHnmDgj44CsYxRd0by1c8x0fAMTR6ukr5Ta/ZPIk+NHnSy+DA0G9dw33EFwSX/5VepfJGzf+4xz7Pbfgxfv+ecBvMAtL9LXcdJMzqUkUQ4N,iv:ZtOWyxdrE7hWPjw+1zxP+rugmUyA89znvikgFcNUw3g=,tag:iDpV3UlcgXV8ufkxjNflCA==,type:str]
    #ENC[AES256_GCM,data:kWuwXhMvRHJgl1j37lSnToyfmH0=,iv:OHhU75MCr59mH1ymb4SVJHyNfxao5lBpIoQacylY4Ic=,tag:qh+bpaRg+4GhAlcuhnzvSg==,type:comment]
    TUNNEL_ID_2: ENC[AES256_GCM,data:q1mkX6/K05tG7JAwBFDDSRSCVUyMSzFlLeIH2AUCAKguB28V,iv:PDT396bJ5v2IOxNLqmNMBLH78gPn/gkX3y/1DYRwxH4=,tag:k0c9MC9SyEJBsvp95U8nMg==,type:str]
    TUNNEL_TOKEN_2: ENC[AES256_GCM,data:eBzt7/acn3ujEKOW8b3vFO7InqtCuOhdAj75Dd+3rB/84YM1ueV5ZXGoxnM/4zh/oyz8kE01qj9swtQclolIEoJKGorQ8J5Mo4kdIwwjXn6r71DZff/4bdSxB/41Q15VDgHgao1hpJeYqyRGD1giwpVKrTtBf5kUCi5zcsMiUGwGGnWlNOIo0Z2UgUliaLMvVpG5KYLpqm9njtwlrMCmtCDxdNw3cM0ZrAH6a0OhQrYeTu4Z,iv:34ShwIsGJm3Rh5R6gpscULnSzCQcgdXKBauITUzCLbQ=,tag:5qDwBmzp0L1cov3zZUr8Ag==,type:str]
    #ENC[AES256_GCM,data:QGzHXr5Tb3EQfCMBT//RVnA=,iv:hlxsPuPRBkQXelJ9T06lhkXx2CP5eE6JQ5WcqTQBGVE=,tag:stjbSHP4V045kv8KCjkQlg==,type:comment]
    TUNNEL_ID_3: ENC[AES256_GCM,data:57tXuT70bdboltrtNNEdIxJzpZ5EQxfAzfXdxAkT1ND+eE0M,iv:g/hTogxWFCaTNEMs3kDNGkZhvxd7HsUTm4Uc+XdYv20=,tag:wy7aRp6O0iLrnArkZXqJ6Q==,type:str]
    TUNNEL_TOKEN_3: ENC[AES256_GCM,data:puHj0CpGVuawQ8R3SWVjbhSN6/Sr+L/aq4bqrjYi9XgWjgPF5K2kgx8CjPX/1B3EBpYal7i3P79/itW/715CmqlidnBAsE4OrJ7uwqwJRyC5qMGUgqUegy6wmj2ZZS7+YItgSmGwYaff/1wLZvBb/FRyZRugrvyFuTV7JO13CQQH4PsHeAEg0I0VhrdJf7qQRp+RzFmGuZX5G2SV6qN+mawb+x4ut/Mp3Jw9fb7R2IOULJC/,iv:absTb971OLCnsuq+XPbxFQFjoZeQkdAtts0uJURXPA0=,tag:CNR+hWrKyk9aQJWZTOyLTw==,type:str]
type: Opaque
sops:
    lastmodified: "2025-11-26T02:40:27Z"
    mac: ENC[AES256_GCM,data:jjXeKUUVq/7AWkZEnD7VNLpGRwacphdh7UNAybj1j8lOmAyDgA12E96nqJfnKIEyi+yJvB+yTC3IuH7q+AZEHAFYa2ZqO8h2FLoOsQUAtatrnRhJoIBm7JeOnSNdzaVgPe3TQ7qgp1G7JL71S92eEBIZSOssYD+UWjN5kHPEsrY=,iv:5y5CrUvUsmD9TJyyBDj24N0c7GZCraxgVLSsXmi5Q0c=,tag:jZ2xSu5BBGkJkocNg4/uew==,type:str]
    pgp:
        - created_at: "2025-11-25T23:48:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMEXnm59zB0kD8zXUuq9g+3Yp3zpxRdpbmmhjIMA6koGKgY
            rkWW/K0vrlqYNP1qXQQRC6E3JN5mBULgtipLyaqE9DCF5+B7w3Lu5kI8//p4HvzF
            /LbFOplkQAcLmhNxlZAQrEnexNt2AQJRQOGoJI/KtCPUaAEJAhCRVgDTdbyAKpaE
            /Q9h/BtF6h2zYUSs3hUNdGXxmIlT39r0rAZ1sifc4XV8Mkn4tGBUuS2oLIqhFbCG
            UKE7cLybxl69kiLQWplwSuRl/erbba4PLPiW7dYQMlKnk6NJXI2uLKzw
            =Jgdx
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-25T23:48:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwMEL+Kr8j1IjYSifLG4Y0r7eIhZBLeYsI74NxlOUh9cCGga
            zURlrJSNbbyTJ8Rf3lOLpob+iexFz50uCcf0DTR7DLbXUS8l7NfiaNMy41JR6uzH
            4E79t8vRjHfqsgA6aJjWMBdTij4ckKy3HHGlsgUA4Axs55BfqnESoZxzQ7pbTAPe
            L4ny4deefxLRivXfgD85JtRoAQkCEKS70tnPFLgW8ll4LLMauO9Qy8ylwT32Tdtm
            /5HbCxO31XnPU9kaUuqcCGOEVGSPRyFWeoohgSETJvq0k5edEO46VgeCNG6KJjrg
            ITwRjJMVb4Q7xZ8VTMEROd94MG1tMPrEvuI=
            =jt4y
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
        - created_at: "2025-11-25T23:48:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DN0J0rS4wp7QSAwMEQsWt5EY6DE3qPhWkfHoTHdDA2Hz/3snjaxO9izB1Av/U
            9KDHT+BHPLGTnhNRetaNl36dV+liSHVwdBgq2zko0imHkJA/9MsJ2Ml5ivILM6Oy
            Dj4JJ6qIo2JOD0GM7X6EMDhVpmpWRuOxLUGLs6hrpUNTY9uNhnFab9RuQS4dmgEd
            hS5Ut04bhXD3JsrU6mKHZdRoAQkCEPcMRcvhPGddKy6aYr2T5F9czBPnOPXsMMCv
            Bx8Mq/quxUUlEwzL5RpmfBkNGKSeLw7fdfeXlmKZ46rYWw3sXwmrEDFoHZEZZIxP
            ROEqEDdP1O8EQuuYXAzd/jnGR7qoSvMZdZE=
            =vAVI
            -----END PGP MESSAGE-----
          fp: 767B1632A4331A3E3828FAA0E490F1F2A2B9BD10
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
