apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: storage-namespaces
  labels:
    app.kubernetes.io/name: storage-namespaces
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: storage
resources:
  - ./rook-ceph.yaml
