apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: storage
    helix.sinlessgames.com/owner: platform
    helix.sinlessgames.com/layer: infra
    sidecar.istio.io/inject: "false"
  annotations:
    helm.sh/resource-policy: keep
    cert-manager.io/disable-validation: "true"
