apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: observability
spec:
  interval: 30m
  retryInterval: 5m
  timeout: 10m
  wait: true
  prune: true
  path: ./IaC/kubernetes/apps/observability/tempo/app
  targetNamespace: observability
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: grafana-mimir
      namespace: flux-system
    - name: loki
      namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
        optional: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
