apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-sync
  namespace: flux-system
  labels:
    app.kubernetes.io/name: harbor-sync
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: platform-harbor-sync
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  targetNamespace: platform
  commonMetadata:
    labels:
      app.kubernetes.io/name: harbor-sync
      helix.ai/component: platform-harbor-sync
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/platform/harbor-sync/app
