apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-reference
  namespace: observability
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - echo.${BASE_DOMAIN}
      secretName: echo-ref-cert
  rules:
    - host: echo.${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-reference
                port:
                  number: 80
