apiVersion: v1
kind: Service
metadata:
  name: echo-reference
  namespace: observability
  labels:
    app.kubernetes.io/name: echo-reference
spec:
  selector:
    app.kubernetes.io/name: echo-reference
  ports:
    - name: http
      port: 80
      targetPort: 8080
