apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: observability-namespaces
  labels:
    app.kubernetes.io/name: observability-namespaces
    app.kubernetes.io/part-of: helix-platform
    helix.ai/component: observability
resources:
  - ./observability.yaml
  - ./performance.yaml
