---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: echo-server-1-allow
  namespace: kube-system
  labels:
    app.kubernetes.io/name: echo-server-1-allow
    app.kubernetes.io/component: echo-server
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: echo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server-1
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              - "/"
              - "/healthz"
              - "/metrics"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: echo-server-2-allow
  namespace: kube-system
  labels:
    app.kubernetes.io/name: echo-server-2-allow
    app.kubernetes.io/component: echo-server
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: echo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server-2
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              - "/"
              - "/healthz"
              - "/metrics"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: echo-server-3-allow
  namespace: kube-system
  labels:
    app.kubernetes.io/name: echo-server-3-allow
    app.kubernetes.io/component: echo-server
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: echo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server-3
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              - "/"
              - "/healthz"
              - "/metrics"
