---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: echo-server-dns-endpoint
  namespace: network
spec:
  endpoints:
    - dnsName: "echo-server.${DOMAIN_1}"
      recordType: CNAME
      targets: ["external.${DOMAIN_1}"]
    - dnsName: "echo-server.${DOMAIN_2}"
      recordType: CNAME
      targets: ["external.${DOMAIN_2}"]
    - dnsName: "echo-server.${DOMAIN_3}"
      recordType: CNAME
      targets: ["external.${DOMAIN_3}"]
