apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./networking
  - ./mesh
  - ./platform
  - ./storage
  - ./observability
  - ./security
  - ./dr-chaos
  - ./cost-feature
  - ./helix
