apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: networking-infrastructure
commonLabels:
  app.kubernetes.io/part-of: helix-platform
  app.kubernetes.io/managed-by: fluxcd
  helix.ai/component: networking-infrastructure
resources:
  - ./namespace.yaml
  - ./coredns/ks.yaml
  - ./external-dns/ks.yaml
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
