apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-staging
  namespace: flux-system
spec:
  interval: 10m
  path: ./IaC/kubernetes/apps/staging
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: mesh-base
    - name: platform-base
    - name: storage-base
    - name: observability-base
  sourceRef:
    kind: GitRepository
    name: flux-system
