---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-config
  namespace: flux-system
spec:
  interval: 1h
  path: ./IaC/kubernetes/apps/base/network/istio-config/app
  dependsOn:
    - name: istio
    - name: cloudflare-tunnel
  postBuild:
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  wait: false
