pyroscope:
  replicaCount: 1
  disableSelfProfile: true
  extraArgs:
    log.level: info
  service:
    type: ClusterIP
    port: 4040
    port_name: http2
    annotations:
      gethomepage.dev/href: "http://pyroscope.observability.svc.cluster.local:4040"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: "Continuous profiling UI"
      gethomepage.dev/group: "Observability"
      gethomepage.dev/icon: "flame.png"
      gethomepage.dev/app: "pyroscope"
      gethomepage.dev/name: "Pyroscope"
      gethomepage.dev/widget.type: "pyroscope"
      gethomepage.dev/widget.url: "http://pyroscope.observability.svc.cluster.local:4040"
      gethomepage.dev/pod-selector: "app.kubernetes.io/name=pyroscope"
      gethomepage.dev/weight: "10"
      gethomepage.dev/instance: "platform"

serviceMonitor:
  enabled: true
