apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-observability
spec:
  interval: 30m
  timeout: 10m
  releaseName: jaeger
  targetNamespace: observability
  chart:
    spec:
      chart: jaeger
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: jaeger-values
      valuesKey: values.yaml
