apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k6-operator
  namespace: flux-system
  labels:
    app.kubernetes.io/name: k6-operator
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cost-k6-operator
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  targetNamespace: cost-feature
  commonMetadata:
    labels:
      app.kubernetes.io/name: k6-operator
      helix.ai/component: cost-k6-operator
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/cost-feature/k6-operator/app
