apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cert-manager-issuers
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  interval: 1h0m0s
  retryInterval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./IaC/kubernetes/apps/cert-manager/issuers/app"
  prune: true
  wait: false
  timeout: 10m0s
  dependsOn:
    - name: cert-manager
