apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo
  namespace: flux-system
spec:
  interval: 1h0m0s
  retryInterval: 2m0s
  timeout: 5m0m0s
  path: ./IaC/kubernetes/apps/kube-system/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        namespace: flux-system
  wait: false
