apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dr-chaos-base
  namespace: flux-system
spec:
  interval: 10m
  path: ./IaC/kubernetes/apps/base/dr-chaos
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: storage-base
  sourceRef:
    kind: GitRepository
    name: flux-system
