apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system
  - ./kube-system
  - ./cluster
  - ./network
  - ./observability
  - ./cert-manager.yaml
  - ./istio-config.yaml
