apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-token
    namespace: networking
    labels:
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/part-of: helix-platform
        app.kubernetes.io/managed-by: fluxcd
        helix.ai/component: dns-automation
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:kg/ekUAMoxNN3Jvw8ts7o6W+67rxTHHyGMqfgHXOMFcdyO442g==,iv:Ja4N/QjqeIaY0srzzz/QFB7bPmjePD2lkiTehNTHv28=,tag:KxCTY3ZTKqEodLDXhRry1w==,type:str]
    email: ENC[AES256_GCM,data:QQlyeYMzycjLFUVkf0aX6laWV1z21E8=,iv:m/hL/z2IpVX8I3dpdGGGUblxS5UfSG519HwfrdEmWfY=,tag:VELRRxDlizd2tafoq4CINA==,type:str]
sops:
    lastmodified: "2025-11-24T07:01:51Z"
    mac: ENC[AES256_GCM,data:c5lT9Aox0upFz8gfx7jDv52ft4AE1MUWKtCVUHR+47+IP3+lXlEGyzuJnnwLYpDjk4wZNGdQoaJT1b+YyByUDt6v3aLTlC4AAA3mfTNVlidI1NnSlKrBZ9ZLpTfOblw4BD4w1vatpf8j6kWUDwhwmf6A8OX7Iw0awbdRYbNB4vU=,iv:d1H+OuRMtpdUgQutuph5RY7YWWtPZPWTz8gO1eftJFk=,tag:9YEHq8rCpYoSg3S615TjOQ==,type:str]
    pgp:
        - created_at: "2025-11-24T07:01:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMEMis5sHitfAE6S0Fzpl/yaiJscljXzOObKwAAkx4BYKkk
            qq2es5+s44jfC7wZgUof8OdZkqmUwxJYLAuZwF8k4TCy1a6QpUllcvEQKx9wBTSt
            /By49QfnPMqSfDhijLGMJZ+OP1TpEVtFG+lCiaLd/I7UaAEJAhCagEpoabUoRqi6
            qgnq3OWIHq1/cqpJqRb0AApID5jtAYMd1qQWoCJRyADE3I1xMVO1Gojwp+fjMzeQ
            r2JsgD9KlkEkMkiWPR7yQoUwd7Heq0QZ8RNJtIFYf+msmfgnalD3i7jT
            =iS1X
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-24T07:01:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwMEZJmA9qg1dDAphHHhz7+lxbuF2gU0Xy/70AiYGkSlWdUS
            muxB4OcpYbYSmOHklOiuLQrjBc1bNw3QK4IicGvCMfYBTJOl8YwYM+6ftDQS+n5Q
            030tvRoR6VBVepejEuNfML25J8bMdCAppInwkoVJzRAa8JhAnuYXhBGqRkQx2/cZ
            dvA8rpvEjC4gn04M/E1pONRoAQkCEN2C7qS74RgBNcM/qXGAK8Csbeuesbiy5duH
            uq6h+dxw7c1q2Tss9PSYsLN+YmsII4gS0Axk8EA0RdtvZkw5tJQVU4T6iE5FvWuS
            wrMSGz0n7Znqycp6731DpSiClt2HleQYhM8=
            =BMzm
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
        - created_at: "2025-11-24T07:01:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DN0J0rS4wp7QSAwMEe0beImnAhGsXLctBOr4d/jlJMYHDfsa/DYo1DmmXS5n9
            TZHcvMSDyxetgRfqucm4jrO9OMXdZrEkca2OBAG28MUMAMZdp+OxCWlV0n+rmjRE
            NMF3Mka0+UIExyOK+Sd0MBRL42IuAf1w54sTeMY17X5mQHKiKoJNB1iHF1FuP1J0
            MDBfHZ4/1Uy4noBhxVuM19RoAQkCEECPJlG0uqXZ9rBW3TfiM2yILvCuPAnYYHJ+
            dfn4wEqaZweq2ULYd2J0BhRACxDdUKZKIvSw8jVRyhYBL5FJWeYcyxIvvt9uQ6CC
            NwDqxESw4gPHTSfjVtLwk5tReLj1Sr61d8U=
            =JmBb
            -----END PGP MESSAGE-----
          fp: 767B1632A4331A3E3828FAA0E490F1F2A2B9BD10
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
