apiVersion: v1
kind: Secret
metadata:
  name: external-dns-cloudflare-token
  namespace: networking
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: dns-automation
type: Opaque
stringData:
  apiToken: 9c5e44bf615080da1d27ea9e6656a6e856de8
  email: disdainful777@gmail.com
