apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-token
    namespace: networking
    labels:
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/part-of: helix-platform
        app.kubernetes.io/managed-by: fluxcd
type: Opaque
data:
    #ENC[AES256_GCM,data:+/PVY58fAEOh1rFMOyd6x6V36TqsRkin8AlUlw8ugcbBs2QyIeLs5gzs6psMAMH4QLrS8fsfktK5xXjUXuvPEvY=,iv:j7smJFObp6XbMxKp+KE9yzi/gc3x23dfSuXMCVRV2zg=,tag:r7jyNyDEjZU0fwZOn7YLkQ==,type:comment]
    apiToken: ENC[AES256_GCM,data:OBLeJYzpc6Qtqrqhc4nujnvN3No7GH26WYKxojqxCTTMG2BO9w==,iv:tFPd1Hv1Be6GcYhWd1wJMOhXQ6vVcqpkxkpzPb86ioc=,tag:X2TPyI/+l5B8/aabkPnV/A==,type:str]
    #ENC[AES256_GCM,data:ditztY4vGjeFdiQRjae97TCxlQiSSW0oxIk7BCJAM9UMrKliER6673sS7I9kYkC9Wes=,iv:AqATeSNfwH6+IpyQFjqz3AQDndoxbVNQTcvQ2OZHUqE=,tag:ZCnju1u5Dqa23jMTw5hQyQ==,type:comment]
    email: ENC[AES256_GCM,data:lS8kasbXlWIGGD7Fwsk5pAgRQ7MgQHQ=,iv:jV+N+BTXTbC96l8qyas/vhu2CgvaCgKnt9+Nu8EOivY=,tag:LnEfkeqA1bmSMwfA8zEDXA==,type:str]
sops:
    lastmodified: "2025-11-23T23:55:37Z"
    mac: ENC[AES256_GCM,data:nKAafmMPF0BonRz3VovUjDoZoXiDzy+cx0ipbdRrqeHxTe0dyxPb1amyxUiH+wnDxnLVTkN+2uTpwJqv7C4WW5AQshPFFy237EGoNgfQn/GFrB77/XqODTdTdmGYJbaAIKnIa1z5M3Cryeh3aEayixDnHWTCPb8+NCgddMF4JsA=,iv:fQDxeLkTe3Zs0m1MEmdkNBswFmjQXG3XrfRZLd6uh7w=,tag:JxPUkTsX4tgjKy66OHBYDA==,type:str]
    pgp:
        - created_at: "2025-11-23T23:55:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMEJHm2WTrhNFslub0zNq8fhjDDxn4mVO/f8LcC2eoDUQUM
            PhpYxfguHWhsz7SVo9z/CVciZ/CmZBQOb54C64wkQjBVDEc848hXg5fXJ15pvDlK
            GExJqHFCTYxmA4fKmvu9O/l9blUJOK+fzUN5ghqKFB/UaAEJAhDWA56MqWsSTskm
            hnJj5rvKy9v/kXEYh8WvC53vIIo4aaGH3gSmfCajU29hNPodVB5qzqn+ePOoUsqT
            iXkFTfJ2DZx0vYrn1O1KgZufKZ5NRfjU8CONDVRy18MIzoa2Hs8fLfgi
            =FaKQ
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-23T23:55:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwMEjQbP48/Hkg+bN4Um7qtdARdUNIpFylXD4abEL3gSQscE
            F7WQs4lVw8zMUdn980THcaxvEb4W+Cum0kvmZZCxByNiaBmAQUjAdvve6GT8gGJ5
            OBhviIapS+75WykbR+e6MJ+UdCqBa7kImvz+g0kH/kEWbLHjp7GclLVSPYr/yo9r
            XDEYNFMeIlwBIGdzdn47ntRoAQkCEKpuN7Q6jwsWjh47IGvTLL9EPQG5xq6BwYxh
            DSsrP+7MDVCQ7YZGfuVa3nROnpGBAmfkNCX4BtA2jlhJzHZ8Ex+AA+2ZtG3RTUw/
            4mmg7s/UsqQzwdYs1VaiVHVeMGj5jDyXYWo=
            =Sx3B
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
