apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
    namespace: network
stringData:
    api-token: ENC[AES256_GCM,data:ULxC5eck0Qz0V+sRU8pM2CdHSvx6WFgA+OhoWozxJS2fh/Ubbk5zFQ==,iv:N81q7BxaMTcSuMVPURvLYEmSqqwCpLuFilLuPLJfz7o=,tag:o31bX5Kxt7eek2p3xbhqyQ==,type:str]
sops:
    lastmodified: "2025-11-25T22:30:38Z"
    mac: ENC[AES256_GCM,data:T6DnnDN+K0E/GSdqKYGhEJ0oP7aodi2ggPnqzWNR0yHXjzojQvt+Se3gEh4VYyi8QKSCtUpReVqjvWE8N+dbz5MSYA6bfWSgnfmvWBQBl49SNEKHdyKcxY7OIMfTzHyDJKJVqgnySFHk+oklEGLSdFCKcLaTt4vyR3Z+C/gyvDk=,iv:hesSGiYEEZc6DbLWcEgCQ0OGmN7W5MBMlUSvmfRJ9Bs=,tag:VmQU81NPOiIC1UUHB1eQ6A==,type:str]
    pgp:
        - created_at: "2025-11-25T22:08:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMEUcUSqOoqWkQLTAPluIRxi3BF7rWXuxr4uP4P3MJv99lB
            dpdq4EMJKbylEQZHSirdOEwrB7q6t2DzJR23TKxJYDDfkeD684C3N1MdlakFfjRh
            Dp8punP+Q8wlZgyYbXhGcPN824T5WSqL0cVK1Ly1iPrUZgEJAhDYdIe7jOxF4Jmw
            OqE/Ml3WO8zBBDQeGI5qoBVvCq8A4yqmzuepGh9bbG6WgXDyifMvJkQ0TPgqlH83
            dgWhb9KGHz9UKe+R9Azj2bNtc2ERwME+IJLFjZFsGXYEjcMM2/0X8g==
            =hHSm
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-25T22:08:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwME8wvuOvw4EDwmHjbRrBMR9UGbiZFIV1FhoxFEZtYrHWfK
            /b+pmiZ+I7PGzVHrnQuh8Gic1heVHYqQRQeJvenIlEKgAzYcodTK8juGgynJoquC
            SjgH3Tn41LQZ5l6sJTZUMHrp1Y8/akUm1GGOxmmlTqlKh7aWEPXJmBTbtisBpyDy
            LPrps5kNUoxwDaRk/2o9mNRmAQkCEG4D1KuA9Zb70WiB/fuIXWLeiOfWEYADxyWQ
            +EPS2ZAYmhYyWXqyPZMQlJJVFa93/lSypQw4kCstG8lFGWKgNhN703SeLfIiveeo
            iu+vlPw1ugM6U9n8+YOZRWfbEdc+sldn
            =Budk
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
        - created_at: "2025-11-25T22:08:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DN0J0rS4wp7QSAwMEwytjwO4KYbR4oQrp++x4i0n4VSr30CbiZIAwU7vsFaa0
            YWaa8jUEETnlXHeAt8+u1EH6oH9o8Nwaz8O8OmleJXIE3BdwWg65HuB4sme9IZsw
            anZaJfEliFZG9cqJI27aMNYvg++n6sE1dsQgB9pGco9Hn1xSOsT5SDLp+vUVSKve
            hPCkXaORjjJYjdpczI2ZZtRmAQkCEL4ifIobt+WL8ZNcb3YG8qgzzLfdVWqFYNWm
            JfNB9Li7eKrfmTrQGSvKzN217D6MPrOzCpxLbvCHdHiI53hwjSVK5fyVQ6FobqiQ
            iew4qbVsZox/iYukJUCcZRxwCogf/BHQ
            =WylZ
            -----END PGP MESSAGE-----
          fp: 767B1632A4331A3E3828FAA0E490F1F2A2B9BD10
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
