# IaC/kubernetes/flux/vars/discord.sops.yaml
# Encrypted via SOPS; do *not* store plaintext secrets in Git.
apiVersion: v1
kind: Secret
metadata:
    name: discord-notification
    namespace: flux-system
    labels:
        app.kubernetes.io/part-of: helix-platform
        app.kubernetes.io/managed-by: fluxcd
        helix.ai/component: notification-secret
type: Opaque
data:
    #ENC[AES256_GCM,data:seKmhwpQswIbtD0jA1X1jbj68Rapy+a1UvAfYd+KkbY=,iv:uCE7iwpzGFg1+Vejuh31HelE254cak5nq23KbtMJI8M=,tag:yaxfynn+yLfp5ZvXMhhWMg==,type:comment]
    webhookUrl: ENC[AES256_GCM,data:R1RymfjpateL/vJhnXtYyP0b1Y0xkXFljrnOxuAb8pPceqWy/mm+Sc1cdNGJapL7r051LDoWRhmKe6Du4bdaFFnvG1w7QZ6C1djMVCCbA9QqlnZeQpFJschiP7V/a3W1yDavDc2yK0zlowrP/NvUASkeBeD5LVWXmyt24A==,iv:Lh/S2WPFGW/3NqxouTPT90558NkxZgxmxf7zj9kPtZ4=,tag:yQBZNlySlbOyoGzTyc0lFg==,type:str]
    channelId: ENC[AES256_GCM,data:+LF6/XEgFSEdYc8WMH0XWAn1yQ==,iv:zsSiWkdE9MxYCU1GOVFYT0BraQiD5SP+/esdmJI4rBQ=,tag:xemJo6wJiQt0wCOqsjObUA==,type:str]
sops:
    lastmodified: "2025-11-23T22:45:05Z"
    mac: ENC[AES256_GCM,data:3Ufd0csLaGae+GOC5rKHthzt8Qa6NpRyBICuPBgcZ5GzxmjQhD+eIBVc2+/uulCSdGRsCxSKFn3J8qnQyeYZnIA1dIaFjBY9VTl0mc3xStbvegI2fUlZi7RHuA9ediwtTokd3w688FsjGh3TgwmJmaUyZvqNYCn3c/6Kt0vkMtA=,iv:wN2yMJH59w1Zp43H1n/5jKv2q3Z4c6GswZnqFroCTho=,tag:3ejD/UqA3FJHqNQoHDUrxg==,type:str]
    pgp:
        - created_at: "2025-11-23T22:45:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMEfFMewD4AHYaLvGr0YrBPnptFggBzJyoRw4z45VkAbGBS
            scXJKDyijiP+6smyUvWoK6MtG9QoZMai8+zp0JSFizCo2jfHVb04A/CYfog7gxqd
            aSVgURdFCBPsAqryxHJ90/AkAUcfsXT6icYnPODKDDjUaAEJAhCLwcCu31woijUE
            i22ygzg3D/9B2/jS4Drv15SOMhALNpc+zGU0NWpgye2It4ib8r6UbwBfBOYFpP9E
            byRZZIBWCb9aWvVAvdMoYX/4m6SlC5LaIOc68ohpS2gpDQ9D28v4VEIx
            =LU0B
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-23T22:45:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwME2hTvcOCywXaz3JieL5ncSDprbusygBSFYSx/YW66BcBo
            nQvFQrJjEH5Hsejl13rx/rAyx/4nrH9ifyK2SjUo98pHr2QrvrjH0lq36HOWLvvi
            q68Ca+8H7SXw2q1wxl0WMMrKaUxDT4QLhyAnd3chCTJSHXpBPm6j7YGtnK4x64RW
            8pb2wnVZcQugdpEoyyg8otRoAQkCEIMszfFhnQrjGz8HGlue/qSUuFHrsxMexk4H
            xVLrAP1Dv7b7Kmq3CfBSFVAwInyBjwlULUXxB4GVOnnxBPzloveMJIrhVBRZfaLE
            6TCgvOiqryaLtGdCQB093C76/JjlNlCzS9k=
            =rtW0
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
