apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
commonLabels:
  app.kubernetes.io/part-of: helix-platform
  app.kubernetes.io/managed-by: fluxcd
resources:
  - ./namespace.yaml
  - ./falco
  - ./crowdsec
  - ./kubescape
  - ./kubearmor
  - ./model-armor
