---
apiVersion: kustomize.toolkit.fluxcd.io/v/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai.component: cloudflare-tunnel
spec:
  interval: 1h0m0s
  retryInterval: 2m0s
  timeout: 5m0m0s

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  path: ./IaC/kubernetes/apps/network/cloudflare-tunnel/app
  prune: true
  wait: true
  targetNamespace: network

  decryption:
    provider: sops
    secretRef:
      name: sops-age

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
