apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chaos-mesh
  namespace: flux-system
  labels:
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: drchaos-chaos-mesh
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  targetNamespace: dr-chaos
  commonMetadata:
    labels:
      app.kubernetes.io/name: chaos-mesh
      helix.ai/component: drchaos-chaos-mesh
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/dr-chaos/chaos-mesh/app
