apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alerts.yaml
- buckets.yaml
- external-artifacts.yaml
- git-repos.yaml
- helm-releases.yaml
- helm-repos.yaml
- helmcharts.yaml
- kustomizations.yaml
- notification-providers.yaml
- notification-recievers.yaml
- oci-repos.yaml
