apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: dns-automation
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  prune: true
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: external-dns
      helix.ai/component: dns-automation
  decryption:
    provider: sops
    secretRef:
      name: flux-system-sops
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/networking/external-dns/app
