apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfeature-operator
  namespace: platform
  labels:
    app.kubernetes.io/name: openfeature-operator
    app.kubernetes.io/instance: openfeature-operator
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-platform
spec:
  interval: 30m
  timeout: 5m
  releaseName: openfeature-operator
  targetNamespace: platform
  suspend: true
  chart:
    spec:
      chart: open-feature-operator
      version: 0.5.7
      sourceRef:
        kind: HelmRepository
        name: openfeature
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: openfeature-operator-values
      valuesKey: values.yaml
