apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali
  namespace: observability
  labels:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: observability
spec:
  interval: 30m
  releaseName: kiali
  chart:
    spec:
      chart: kiali-server
      version: ">=1.84.0 <1.90.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  install:
    remediation:
      retries: 3
  values:
    auth:
      strategy: anonymous
      anonymous:
        role: admin
    deployment:
      viewOnlyMode: false
      accessibleNamespaces:
        - "**"
      podAnnotations:
        sidecar.istio.io/inject: "true"
      ingress:
        enabled: false
    external_services:
      istio:
        url_service_version: v1beta1
      tracing:
        url: http://tempo-query-frontend.observability:3100
      grafana:
        enabled: true
        url: https://grafana.${DOMAIN_3}
      prometheus:
        url: http://kube-prometheus-stack-prometheus.observability:9090
    server:
      metrics_enabled: true
      web_root: /
      observability:
        tracing:
          collector_url: http://otel-collector-gateway.observability:4317
