---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

commonLabels:
  app.kubernetes.io/part-of: helix-platform
  app.kubernetes.io/managed-by: fluxcd
  helix.ai/component: oci-repository

resources:
  - oci-repo-jetstack.yaml
  - oci-repo-coredns.yaml
  - oci-repo-cilium.yaml
  - oci-repo-metrics-server.yaml
  - oci-repo-stakater.yaml
  - oci-repo-spegel.yaml
  - oci-repo-external-dns.yaml
  - oci-repo-bjw-s-app-template.yaml
