apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: oci-repository
spec:
  interval: 15m
  url: oci://ghcr.io/home-operations/charts-mirror/cilium
  ref:
    tag: 1.18.4
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
