apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull-secret
  namespace: platform
  labels:
    app.kubernetes.io/name: harbor-pull-secret
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{}'
