apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-fs
  labels:
    app.kubernetes.io/name: rook-ceph-fs
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
provisioner: rook-ceph.cephfs.csi.ceph.com
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
parameters:
  clusterID: rook-ceph
  fsName: myfs
  pool: myfs-data0
