apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - echo-server-1.yaml
  - echo-server-2.yaml
  - echo-server-3.yaml
  - dns-endpoint.yaml
  - authorizationpolicy-1.yaml
  - authorizationpolicy-2.yaml
  - authorizationpolicy-3.yaml
