apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - echo-server-1.yaml
  - echo-server-2.yaml
  - echo-server-3.yaml
  - dns-endpoint.yaml

patchesStrategicMerge:
  - |
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
      name: echo-server-1-allow
      namespace: kube-system
  - |
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
      name: echo-server-2-allow
      namespace: kube-system
  - |
    apiVersion: security.istio.io/v1
    kind: AuthorizationPolicy
    metadata:
      name: echo-server-3-allow
      namespace: kube-system
