apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: platform
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-platform
spec:
  interval: 30m
  timeout: 10m
  releaseName: nats
  targetNamespace: platform
  suspend: true
  chart:
    spec:
      chart: nats
      version: 1.2.9
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: nats-values
      valuesKey: values.yaml
