apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: model-armor
  namespace: flux-system
  labels:
    app.kubernetes.io/name: model-armor
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: security-model-armor
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  targetNamespace: security
  commonMetadata:
    labels:
      app.kubernetes.io/name: model-armor
      helix.ai/component: security-model-armor
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/security/model-armor/app
