apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali
  namespace: mesh
  labels:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-platform
spec:
  interval: 30m
  timeout: 5m
  releaseName: kiali
  targetNamespace: mesh
  chart:
    spec:
      chart: kiali-server
      version: 1.85.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kiali-values
      valuesKey: values.yaml
