# IaC/kubernetes/flux/config/clusters.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: clusters
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/Sinless777/Helix
  ref:
    branch: main
  ignore: |
    Docs/**
    IaC/ansible/**
    IaC/terraform/**
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusters
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./IaC/kubernetes
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: clusters
    namespace: flux-system
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: flux-system-sops
  postBuild:
    substitute:
      CLUSTER_NAME: "${CLUSTER_NAME:=unknown}"
