apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/helix
patches:
  - path: ./patches/api-deployment-prod.yaml
    target:
      kind: Deployment
      name: helix-api
  - path: ./patches/frontend-deployment-prod.yaml
    target:
      kind: Deployment
      name: helix-frontend
  - path: ./patches/workers-deployment-prod.yaml
    target:
      kind: Deployment
      name: helix-workers
  - path: ./patches/virtualservice-prod.yaml
    target:
      kind: VirtualService
      name: helix
  - path: ./patches/psp-network-pol-prod.yaml
    target:
      kind: NetworkPolicy
      name: helix
  - path: ./patches/hpa-prod.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: helix
