apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cost-feature
commonLabels:
  app.kubernetes.io/part-of: helix-platform
  app.kubernetes.io/managed-by: fluxcd
resources:
  - ./namespace.yaml
  - ./opencost
  - ./k6-operator
