apiVersion: v1
kind: Namespace
metadata:
  name: cost-feature
  labels:
    app.kubernetes.io/name: cost-feature
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
