apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
metadata:
  labels:
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: networking-tunnels
commonLabels:
  app.kubernetes.io/name: cloudflared
  helix.ai/component: networking-tunnel
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudflared-values
    files:
      - values.yaml=./configs/values.yaml
    options:
      disableNameSuffixHash: true
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: cloudflared-tunnel-secrets
    files:
      - secret.sops.yaml=./secrets/secret.sops.yaml
    options:
      disableNameSuffixHash: true
patchesStrategicMerge: []
