apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: networking
  labels:
    app.kubernetes.io/name: emissary-ingress
    app.kubernetes.io/instance: emissary-ingress
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-platform
spec:
  interval: 30m
  timeout: 10m
  releaseName: emissary-ingress
  targetNamespace: networking
  suspend: true
  chart:
    spec:
      chart: emissary-ingress
      version: 8.7.1
      sourceRef:
        kind: HelmRepository
        name: emissary-ingress
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: emissary-ingress-values
      valuesKey: values.yaml
