apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: echo-service
namespace: networking
commonLabels:
  app.kubernetes.io/name: echo-server
  helix.ai/component: echo-service
resources:
  - ./helmrelease-domain1.yaml
  - ./helmrelease-domain2.yaml
  - ./helmrelease-domain3.yaml
configMapGenerator:
  - name: echo-server-domain-values
    files:
      - values.yaml=./configs/values.yaml
    options:
      disableNameSuffixHash: true
generatorOptions:
  disableNameSuffixHash: true
