apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cilium-config
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: networking
spec:
  interval: 10m0s
  retryInterval: 2m0s
  timeout: 5m0s
  prune: true
  wait: true

  path: ./IaC/kubernetes/apps/kube-system/cilium/config

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: cilium
      namespace: flux-system
