apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spegel
  namespace: flux-system
  labels:
    app.kubernetes.io/name: spegel
    app.kubernetes.io/component: kube-system
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: spegel
spec:
  interval: 10m0s
  retryInterval: 2m0s
  timeout: 5m0s
  prune: true
  wait: true

  path: ./IaC/kubernetes/apps/kube-system/spegel/app

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: cluster-vars
      namespace: flux-system
