---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-server-app
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: echo-server
spec:
  interval: 1h0m0s
  retryInterval: 2m0s
  timeout: 5m0s
  path: ./IaC/kubernetes/apps/kube-system/echo-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        namespace: flux-system
