apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 1h
  path: ./IaC/kubernetes/apps/base/cert-manager/issuers/app
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
