apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-config.yaml
  - cilium.yaml
  - coredns.yaml
  - metrics-server.yaml
  - stakater.yaml
  - spegel.yaml
  - echo-server.yaml
