apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns
  namespace: flux-system
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: core-dns
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  prune: true
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: coredns
      helix.ai/component: core-dns
  dependsOn:
    - name: cloudflared
      kind: Kustomization
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/networking/coredns/app
  wait: false
