apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: cost-feature
  labels:
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: opencost
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-platform
spec:
  interval: 30m
  timeout: 5m
  releaseName: opencost
  targetNamespace: cost-feature
  suspend: true
  chart:
    spec:
      chart: opencost
      version: 1.31.0
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: opencost-values
      valuesKey: values.yaml
