apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/component: cni
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: networking
spec:
  interval: 1h0m0s
  retryInterval: 5m0s
  timeout: 10m0s
  prune: true
  wait: true

  # Reconciles the HelmRelease in /app
  path: ./IaC/kubernetes/apps/kube-system/cilium/app

  targetNamespace: kube-system

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: true
