apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: cert-manager
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/cert-manager/cert-manager/app
  targetNamespace: cert-manager
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
