apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared-tunnel
  namespace: flux-system
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: networking-tunnel
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudflared
      helix.ai/component: networking-tunnel
  dependsOn:
    - name: external-dns
      kind: Kustomization
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/networking/cloudflared/app
  wait: false
