image:
  repository: ghcr.io/gethomepage/homepage

enableRbac: true

service:
  main:
    ports:
      http:
        port: 3000
    annotations:
      gethomepage.dev/href: "http://homepage.platform.svc.cluster.local:3000"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: "Helix landing dashboard"
      gethomepage.dev/group: "Platform"
      gethomepage.dev/icon: "home.png"
      gethomepage.dev/app: "homepage"
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/widget.type: "homepage"
      gethomepage.dev/widget.url: "http://homepage.platform.svc.cluster.local:3000"
      gethomepage.dev/pod-selector: "app.kubernetes.io/name=homepage"
      gethomepage.dev/weight: "5"
      gethomepage.dev/instance: "platform"

ingress:
  main:
    enabled: false

config:
  bookmarks:
    - Observability:
        - Grafana:
            - abbr: GF
              href: http://kube-prometheus-stack-grafana.observability.svc.cluster.local
        - Loki:
            - abbr: LK
              href: http://loki.observability.svc.cluster.local:3100
        - Tempo:
            - abbr: TP
              href: http://tempo.observability.svc.cluster.local:3200
        - Jaeger:
            - abbr: JG
              href: http://jaeger-query.observability.svc.cluster.local:16686
        - Pyroscope:
            - abbr: PY
              href: http://pyroscope.observability.svc.cluster.local:4040

  services:
    - Platform:
        - Grafana:
            href: http://kube-prometheus-stack-grafana.observability.svc.cluster.local
            description: Dashboards and alerts
            icon: grafana
        - Loki:
            href: http://loki.observability.svc.cluster.local:3100
            description: Logs API
            icon: loki
        - Tempo:
            href: http://tempo.observability.svc.cluster.local:3200
            description: Traces API
            icon: tempo
        - Jaeger:
            href: http://jaeger-query.observability.svc.cluster.local:16686
            description: Traces UI
            icon: jaeger
        - Pyroscope:
            href: http://pyroscope.observability.svc.cluster.local:4040
            description: Profiles UI
            icon: flame

  widgets:
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank

  kubernetes:
    mode: default
    ingress: true
    gateway: true

  settingsString: |
    title: Helix Home
    headerStyle: boxed
    layout:
      - [ [0,0,12] ]
