apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
  labels:
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: storage-rook-ceph
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: rook-ceph
      helix.ai/component: storage-rook-ceph
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/storage/rook-ceph/app
