apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    #ENC[AES256_GCM,data:XzOifZfLSW3LBqXZcIYQ,iv:DzuirpNymavRMCZlvQ5HdE2sVe7GRgjmbKl6jZwiQQY=,tag:rRF0OpaDPqtI5VapGXa85A==,type:comment]
    TUNNEL_ID_1: ENC[AES256_GCM,data:135Bow3y9nsJzHoj1nMhZ2KeYFivx2wxAg06RKXOTY9tKm38,iv:5OceMXW7sDCov+RRF0LeFb9IfQeBRbE1lfbOJ7pQK/0=,tag:3YqEVqi+JLU991wX3Hjvrw==,type:str]
    TUNNEL_TOKEN_1: ENC[AES256_GCM,data:4H3xF7ILdwFm2axlhHTyBMT/K4jNThSnomEymrVEXA1IMvHBDTD85kdckTw=,iv:moWUdEbVfdbBiMMw7oa3Ku7l3iyTh5uH6FQ/+tor4J4=,tag:UF6CH/DopmlKnEkRbp3UMw==,type:str]
    #ENC[AES256_GCM,data:kWuwXhMvRHJgl1j37lSnToyfmH0=,iv:OHhU75MCr59mH1ymb4SVJHyNfxao5lBpIoQacylY4Ic=,tag:qh+bpaRg+4GhAlcuhnzvSg==,type:comment]
    TUNNEL_ID_2: ENC[AES256_GCM,data:21XMn5G5RQJ46szveq4mBKPiHby2gaFhIRBSBabll1KzaIVo,iv:J1a7au+9gK+5m4OoMkGVR+4VmAdt28WVlCUXMFA1VtQ=,tag:smQ823kOwO60fmuFeLAngA==,type:str]
    TUNNEL_TOKEN_2: ENC[AES256_GCM,data:G4Ici+06aC2+SN/XWcLmQ7QZ/EWa+5/MhXjiiOvUPsKshPF4aHHme8RXGZ0=,iv:Aq9gkT8a9GRtVTzRrN7jCYMrx31Fxh+5F7y5VOCcD/k=,tag:zwO1dCTGWDySPuyMGX1RPA==,type:str]
    #ENC[AES256_GCM,data:QGzHXr5Tb3EQfCMBT//RVnA=,iv:hlxsPuPRBkQXelJ9T06lhkXx2CP5eE6JQ5WcqTQBGVE=,tag:stjbSHP4V045kv8KCjkQlg==,type:comment]
    TUNNEL_ID_3: ENC[AES256_GCM,data:6vQ64/L/cH+CC/44WDYz4GoJFrXQBiUWhD3RWzPKEEHLBxY8,iv:huzuJWz+Uv+sCctG8WDa+nBUkWklZOUKVXrgeIVJUBA=,tag:zhAShgCxhSLQSzcQlCDk9Q==,type:str]
    TUNNEL_TOKEN_3: ENC[AES256_GCM,data:xI8j9ZF/c+46QJDxO/K2ihClWCeTP0Tuw29UM8IwuteuZS/dwdomCC7ZzJg=,iv:2SRXCPgSQ3gk+mUDqVdBYPxG2R8mw1HfwnmQMxT+EXM=,tag:Lm4hI4LDu79dLt+y0YNvtA==,type:str]
type: Opaque
sops:
    lastmodified: "2025-11-25T23:48:46Z"
    mac: ENC[AES256_GCM,data:fWw7MIfegLraHGzviSo4oxQrg2zz8xXq/o5toxnIXcCpXW3Qg8p+dR1rPSNLMDGAjLpBKtjTFgVzM/XUElDWbs9/VtkgJHI49uyx04OkZ25LcfuQiJU+yOMsokQJAIXGIdpy5yB++5cgPwpfcHeTiuMpnhGbkvumVvDiNja5lyU=,iv:c/8gQYi0sgeXJtKJW6jQwNxUn1+3D4MD9O4h0pXuTuU=,tag:EkCivp3ZcPeB2TSaOfSlXA==,type:str]
    pgp:
        - created_at: "2025-11-25T23:48:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMEXnm59zB0kD8zXUuq9g+3Yp3zpxRdpbmmhjIMA6koGKgY
            rkWW/K0vrlqYNP1qXQQRC6E3JN5mBULgtipLyaqE9DCF5+B7w3Lu5kI8//p4HvzF
            /LbFOplkQAcLmhNxlZAQrEnexNt2AQJRQOGoJI/KtCPUaAEJAhCRVgDTdbyAKpaE
            /Q9h/BtF6h2zYUSs3hUNdGXxmIlT39r0rAZ1sifc4XV8Mkn4tGBUuS2oLIqhFbCG
            UKE7cLybxl69kiLQWplwSuRl/erbba4PLPiW7dYQMlKnk6NJXI2uLKzw
            =Jgdx
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-25T23:48:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwMEL+Kr8j1IjYSifLG4Y0r7eIhZBLeYsI74NxlOUh9cCGga
            zURlrJSNbbyTJ8Rf3lOLpob+iexFz50uCcf0DTR7DLbXUS8l7NfiaNMy41JR6uzH
            4E79t8vRjHfqsgA6aJjWMBdTij4ckKy3HHGlsgUA4Axs55BfqnESoZxzQ7pbTAPe
            L4ny4deefxLRivXfgD85JtRoAQkCEKS70tnPFLgW8ll4LLMauO9Qy8ylwT32Tdtm
            /5HbCxO31XnPU9kaUuqcCGOEVGSPRyFWeoohgSETJvq0k5edEO46VgeCNG6KJjrg
            ITwRjJMVb4Q7xZ8VTMEROd94MG1tMPrEvuI=
            =jt4y
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
        - created_at: "2025-11-25T23:48:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DN0J0rS4wp7QSAwMEQsWt5EY6DE3qPhWkfHoTHdDA2Hz/3snjaxO9izB1Av/U
            9KDHT+BHPLGTnhNRetaNl36dV+liSHVwdBgq2zko0imHkJA/9MsJ2Ml5ivILM6Oy
            Dj4JJ6qIo2JOD0GM7X6EMDhVpmpWRuOxLUGLs6hrpUNTY9uNhnFab9RuQS4dmgEd
            hS5Ut04bhXD3JsrU6mKHZdRoAQkCEPcMRcvhPGddKy6aYr2T5F9czBPnOPXsMMCv
            Bx8Mq/quxUUlEwzL5RpmfBkNGKSeLw7fdfeXlmKZ46rYWw3sXwmrEDFoHZEZZIxP
            ROEqEDdP1O8EQuuYXAzd/jnGR7qoSvMZdZE=
            =vAVI
            -----END PGP MESSAGE-----
          fp: 767B1632A4331A3E3828FAA0E490F1F2A2B9BD10
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
