apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: kube-prometheus-stack-secrets
    namespace: observability
    labels:
        app.kubernetes.io/name: kube-prometheus-stack-secrets
        app.kubernetes.io/part-of: helix-platform
        app.kubernetes.io/managed-by: fluxcd
        helix.ai/component: kube-prometheus-stack
stringData:
    #ENC[AES256_GCM,data:r9cEaVAkkfOcSOqtaWp72tXtHmP8dkhVOry//JGz/03B1N4b7/YRg4/q3Xv0t+myXk3c7v7HJ7RGMRnq2ovaVLgC9xtOxWB9vOzcjw==,iv:/JhAjMcT/0il30TZIQrg2xGQUNbF7CcyfXIG1nf0bBc=,tag:0/KbvIG+dvLpZNErm/6UXA==,type:comment]
    #ENC[AES256_GCM,data:D0n2HRUYzs8xFqCbLqy02V87iEtwBti731c=,iv:/0rvDSOdhXuHpDj9cYkKw9zPo+XEoTOHCS0Om6mkwNg=,tag:xMzjs530ZJkpu68yuP1OaA==,type:comment]
    #ENC[AES256_GCM,data:r9cEaVAkkfOcSOqtaWp72tXtHmP8dkhVOry//JGz/03B1N4b7/YRg4/q3Xv0t+myXk3c7v7HJ7RGMRnq2ovaVLgC9xtOxWB9vOzcjw==,iv:/JhAjMcT/0il30TZIQrg2xGQUNbF7CcyfXIG1nf0bBc=,tag:0/KbvIG+dvLpZNErm/6UXA==,type:comment]
    grafana-admin-user: ENC[AES256_GCM,data:4cbTGON5SIBkBw==,iv:5rO16RVpWpdnEFOVglsHUV865AEni6jaJQy1WDaxyMU=,tag:Kc5mUSyHeQvlYitJNFxJHA==,type:str]
    grafana-admin-password: ENC[AES256_GCM,data:gFL2Y4QyelEyxW32Lao6,iv:v7G5hp1eNwpoEiLew4y7lpMvmZx+tuPRUdJ37KenUX4=,tag:/GZcEkpcPaN8h/uT5KF+4w==,type:str]
sops:
    lastmodified: "2025-11-26T22:12:43Z"
    mac: ENC[AES256_GCM,data:fe+wnU0j0jaO1mCP6amVhbijHWGPVTICgLp/T5orYbXz7d6Ba7fkUlQx+imh5m+3qFzi0uDK9NtDa2JVec3Vnx5qMOdwsqQuWzpVR1VQeeU5L88mOjexFRTBKuMiR7Lm7cU4OjGMrBB+tfYyKkiEOaY8MarnOrK5FR5+BW7s0OM=,iv:knLQ8C3fYbcKMEjjHd8wTNZZ6SpYidOlwTeIbiVZ+0I=,tag:mAYjGr/2frL165H/zQBOSg==,type:str]
    pgp:
        - created_at: "2025-11-26T21:19:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMEbXNm5Rz0uTjknpAXNlut8qsoUNeMdN5Jqsqm2LQGIXdG
            sIPyJ3mVoHbnPpe4SwEQT3jaZebW1/3z8tPcmxRccjCapsbz/RzxzqMRAmOi5Zqi
            1o4agncZFgkqxflrmcl6bWlue1zUi/GLThQ9NvS/FzHUaAEJAhAPtNWgsSIpv8/Z
            JUuTvLGzlSxcNdMrzxCcReUaE6VzHmmKyqIOo3xeGABmzNkQxwdsJHqztw1hLLB5
            l0zZd3DkI3Yu7v2JV/rjl1wdhSAcdZdKued2gsq8c0iy4HriGanrRif6
            =MRC6
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-26T21:19:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwMEXxXWR9vQDzRIf/4jBSAVmIpr/QMziCnc8rB61sUmA9Rg
            q34H8TN5rsxnLAw9j3WrMIoM5Ru7iuZngSBv5mlHeJnGqLIupMZSGvx6cPccoQqu
            UufZgutlu/OXPHzaGQ6KMPgvXLrKUlz6NO0Z0bghu+0lS/spz5cbeU3jX+QDei8D
            RTK0gqRnQsl5tAJmGXsUNdRoAQkCEA8r28XUw7Io1lUO0AmOEhebNnrI5e3Z/GFq
            HGJmEEjoQIYfUfwFQgvLS6PXlsum59quUuQuNP16LJqeOjqy/BalnpaBitapwJUp
            8sCQAuL1aLPuwoweAxZ0PDWXWYCiVbNhn68=
            =Ipz7
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
        - created_at: "2025-11-26T21:19:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DN0J0rS4wp7QSAwMEtv22NLhvSYbS30S4BVZoWVrnlMdjg5twUuTEcqu+LcX7
            zUHVItFdzX5P5dzilrdqQIp0E02tOhmgs40+GtV3v0yTSyqDM5nBRSW8iwSgJI4D
            pDO4yjTNvH4PVH3rv7iXME+vxf6Hlwiifb9ckTLOrvgjwe4I6DF/auvyINwusI+G
            rWLONC6nJK7yEpZQp6HRl9RoAQkCEGD/j7FhCdGe0/JfEm5yAx6FPdz7d7xIF9GG
            PPF9HCBqdRM1H4hpjabIGPktbqPFO5E5aauyG2nLyopyaDPnFNyM2CAoh+L/mW2v
            zBcmsBNC9S7QfCY+3OZtg+eoOU3aHoZO5tM=
            =tjKv
            -----END PGP MESSAGE-----
          fp: 767B1632A4331A3E3828FAA0E490F1F2A2B9BD10
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
