apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: network-root
  labels:
    app.kubernetes.io/name: network-root
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: network-bootstrap
resources:
  - cloudflare-dns.yaml
  - cloudflare-tunnel.yaml
  - istio.yaml
  - istio-config.yaml
