apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-team
commonLabels:
  app.kubernetes.io/part-of: helix-platform
  app.kubernetes.io/managed-by: fluxcd
  helix.ai/team: platform-team
resources:
  - ./namespace.yaml
  - ./rbac.yaml
