apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-team-admin
  labels:
    app.kubernetes.io/part-of: helix-platform
    helix.ai/team: platform-team
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: tpierce@sinlessgamesllc.com
    apiGroup: rbac.authorization.k8s.io
