replicas: 1

tempo:
  multitenancyEnabled: false
  retention: 48h
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

serviceMonitor:
  enabled: true

persistence:
  enabled: false

service:
  annotations:
    gethomepage.dev/href: "http://tempo.observability.svc.cluster.local:3200"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Trace store API"
    gethomepage.dev/group: "Observability"
    gethomepage.dev/icon: "tempo.png"
    gethomepage.dev/app: "tempo"
    gethomepage.dev/name: "Tempo"
    gethomepage.dev/widget.type: "tempo"
    gethomepage.dev/widget.url: "http://tempo.observability.svc.cluster.local:3200"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=tempo"
    gethomepage.dev/weight: "10"
    gethomepage.dev/instance: "platform"
