apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k6-operator
  namespace: cost-feature
  labels:
    app.kubernetes.io/name: k6-operator
    app.kubernetes.io/instance: k6-operator
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-platform
spec:
  interval: 30m
  timeout: 5m
  releaseName: k6-operator
  targetNamespace: cost-feature
  suspend: true
  chart:
    spec:
      chart: k6-operator
      version: 2.1.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: k6-operator-values
      valuesKey: values.yaml
