apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: networking
    labels:
        app.kubernetes.io/name: cloudflared-tunnel
        app.kubernetes.io/part-of: helix-platform
        app.kubernetes.io/managed-by: fluxcd
type: Opaque
data:
    #ENC[AES256_GCM,data:gSW7aidqQmZ17NLqpdkyBA==,iv:72yOvgrRrh8WOJteASfgoX1ekm0LgNPwlfCJ+wlbJ3c=,tag:RziuzwuwfGTBRGM2Pr/+BQ==,type:comment]
    tunnelId1: ENC[AES256_GCM,data:tr5QfubT3RBKCGZUlxvYkxEOv6hNdEAN80QWhSnNUaKgeD1I,iv:YDMOrwC6pg0waCa3HJgPRcRFayDHxLbw5jB30S1fT1c=,tag:dv0rZFgKV44b7WxXBDspqg==,type:str]
    tunnelSecret1: ENC[AES256_GCM,data:Qhvy8Dp0DcUyd9FH/V/nP+zD3uUvaNisZV+CujSetZeclyd3LkM0ZOUMb9c=,iv:A1nOH7CizxJN5zSPWIaiocYSDFUGBAGsL/+iLvPMatQ=,tag:MHdh2+4ZcFJGQfOQ9TfJUg==,type:str]
    ingressHostname1: ENC[AES256_GCM,data:lhM7NEOsTKaCDyk=,iv:nt/7tkJfplpSG/StZ0e3W2z9itHTwhQomHVSJvP2CJs=,tag:OfPjfP+zIz6L3hHReXaXCA==,type:str]
    tunnel_1.json: ENC[AES256_GCM,data:DGPAuPxcKJINRxTW8PbQTVyy8v+9lxPBwlm3Xcr2Pp+ccWZMjUbIGrIWZBWPyGufdiWorKZQA3Odxyr6iSKUqnIQFTako4IeEd5ZnOfXzXgErzcr4BXqVaQ2A7Ot/5fx6waJ42aeho+uFc0WHRAZJJyTW6N0IY+rN8ME9qJqyhzH8lPoDAIbYM1JYtHJ25uPmf95Pej3IV9WL/+tRBgXuEMYu0DdUoHnBRgC3HQd1Z6gAfJgqptLmTXNZEbvuQAWIO8j4p97UWV7,iv:RminkQtgXyDguxizd7QYRZb0JweWGCc9KgyWUbiC1ac=,tag:4EznhZdhorsMXg8VtcIDUQ==,type:str]
    #ENC[AES256_GCM,data:itG7O4q/uKBrw3u93+ClwBQAEjw=,iv:H/a/DJCtjhnak4Zgl+5z4pEJrd0vj7kpTJpE8plmI2I=,tag:k7vG2MEWLiBruhxIC4dOsQ==,type:comment]
    tunnelId2: ENC[AES256_GCM,data:tKHxd3HT25cDGAy9M3FfRhBwWEyedgOVVy36M3yuoVVRp/S6,iv:OYquywvjAa3nFwtm3riUZuGZlA0fITsiB1GBhYvqwvU=,tag:yZWY3B4NF/mXB6838u3jAA==,type:str]
    tunnelSecret2: ENC[AES256_GCM,data:u32S/nubk6rE+jdzDR0rTQe2K7bra5//ST7S5WjV7qRGcd1Ktf8NgJVkOtQ=,iv:d2b883IVM9BqfH2ENYJ+PWDdUZ6WBbL8bEP42T+fsHQ=,tag:EFOtvTbI8ZCrzELUHrNv+Q==,type:str]
    ingressHostname2: ENC[AES256_GCM,data:C3hRuVaS9ZGHopc=,iv:UHgLz01JS0JKq4KPQgn8mWVomw8uYAi7kh/vGncIwvE=,tag:VyAE2N4QZ3xUVFR88Cz10g==,type:str]
    tunnel_2.json: ENC[AES256_GCM,data:ifsOCBrODZmUKmKoI8aeQOI3T5msGYcXlj/HWLEQzGmHgXncUsORx5iEeGEe+NFH1G8sS7ulJrrE5KMofDFO1KvOFsY6bRPIaxvTkoAUePiS7T23uUFPjqRS/JgOz1JpoW5wHHmVDqZ+BBud6B5Gqh2vpiuPwOaWq7ZRP7HxhLK52pM99BYF9xbalv+bafbVmiVfx4kXJeC1zQcwrBYLKpW0DobEZ6D4ei64Lpyyp7rzvaWKPrRckCSV43UxbsWU7hOHOxtdOWEt,iv:HdP3UETGd8lp0znWnhz8zkYl+OVaxvE8LMm9XabwcD4=,tag:P6yyZowGhqB1esxoibMYBQ==,type:str]
    #ENC[AES256_GCM,data:YQjFhb9z2CvDes10mpedaR4=,iv:v3TnAELZwqF6JukKYwYl4UYD4ep28snOr4AI8y3XFTk=,tag:5dwsgEqZKP0ceOqYN9SvjQ==,type:comment]
    tunnelId3: ENC[AES256_GCM,data:iyzaMMcwh6m/uoswaz9TZCgTzVgqp+kps9m+CYzlGJ1yyk2o,iv:m4x0AMc9Suolu0veffOk3M2CBecFx3mDRgrenMl7AL8=,tag:GIZy6R79lO63DsW4D+Hs+g==,type:str]
    tunnelSecret3: ENC[AES256_GCM,data:OCfqjWH5Cj4QKkePdDebFJ/dAcp6VijxtEgvGg0K1AZUsOQ1ibNFT7tr838=,iv:pq26r2LR1y7hZhOG7OJN1+DyVmIYW9MlGW3m64k+kkA=,tag:IM535uWnVjM3c7OldvajSQ==,type:str]
    ingressHostname3: ENC[AES256_GCM,data:EXSCo0eMbAgd0s4=,iv:b0MqjuTZ8/j8A2MkYMzUwe6SE/jv+c3hnHw66h0VPIo=,tag:CDtEJ8Ym0bYC0ngQlrZkmg==,type:str]
    tunnel_3.json: ENC[AES256_GCM,data:+TdROgZEF4Zos36vqtQaiwFCFg98hquSdgRgtwNB7ZolC7qnrZk1wWX5T9HZpF8pSN7FH1SXYkmpYWkZs2D70GxtwgSAOR0mrTgPMcoDk6kYqxvdWNKm2TQHe2S0hYvpMVSLiNl1HFfXQi4et9Ub+6CdYsJuc5jdDS192v1cakBnX6nKoNERyzJr6tydiYyrPrtq5iMcQ4sqI9qKimEqGQh9jCYv+2cy9SHWVxmoLzeUFg2S4m36ucfnCy9NdvvS6mXXF+taih2Z,iv:fVMNH6hDd8dO0q+O6mkC0RBJu8qrKjx4uiMSdsvv7vc=,tag:HITPB6ksHemgfCDpBCFfUw==,type:str]
sops:
    lastmodified: "2025-11-23T23:36:25Z"
    mac: ENC[AES256_GCM,data:5wuqh4d/qQk3yiWqJG1PjEE5kbfI1GWXII+Fubg9KijZV378bKB6oQT91oZRoqaPtlhm2uc28Us7Uk9vY8aM1RYZcUNMPhREciyU6xYqLBCBonCE3Y3U61RQ785HhJdsLUk4y51iqAizdNH2P8/rmEtWIngj/A491744oeZbfss=,iv:ZN3vXsBuDhltz4GbvJlG5zDlUiEV+BBHlSc1mbW1hLQ=,tag:PN9lt5jwZ6PsgLd3ZVflnw==,type:str]
    pgp:
        - created_at: "2025-11-23T23:10:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4Dldw2XLutmfUSAgMEIO644cUXCOXkd3HNn8ocU5hSW0sWffNFfSz6tB37jsxc
            pApaIcqXx2iE97+rhgYLXDMeD6iqyMRmRobgxFDELTAvORtJ1v4GOrQCBaU60ysE
            jdgHxphzRIthFb84yIwnNI01zOD5urd5oI6WyhZnGZfUZgEJAhDk/93OsP9MqcaH
            h6KzjlXs+1FELgmYdrOFE5j1zE6+izQEvzDO6o4wGEOWinJ5JJN95oNv+RYYNg/Q
            NlcyPLtA4APbA8aDLTDUhWEsJuuzgfCNpozcDyuHFIaLi+rlUbJM4g==
            =gDQ3
            -----END PGP MESSAGE-----
          fp: A25EFEA975F16297E0765B25AF60954F70D230D4
        - created_at: "2025-11-23T23:10:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DwouqLDqu8PQSAwMEQfcBMwiVUAev6//UakEb1XUndNUkM0nEIyRHkYVMsQnC
            PnPMT3O8f3p9xDUquoYRr3TumdtQ7NwdDSqCO7N0AnYox+8V+XxsGodDuqA3qib4
            EzlxTolj8Nz3UyVV4pneMEf4LJqWAdfvPzgs12wjY7iomV0l4oOLXPtOvKxT71qH
            0MR5cYUyWSWoupAItn+yCdRmAQkCEI4bTEYJslFnDmoBk2EqaKXdbT+oytp6qQ5P
            H5tggMWB2rf6f5zcyFgJ/1uhEgAHD7g+UPwPVFy0y59tGrpH+mJICUzh88Vv5aGj
            CQtX6BLkan+p6HLs+GKInTdaxWOd+DxJ
            =8lqO
            -----END PGP MESSAGE-----
          fp: DF0A8D61F4818A36E0409C2B295E99E6DD33049E
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
