apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
  labels:
    app.kubernetes.io/name: istio-system
    app.kubernetes.io/part-of: helix-platform
    app.kubernetes.io/managed-by: fluxcd
    helix.ai/component: service-mesh
spec:
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  prune: true
  targetNamespace: mesh
  commonMetadata:
    labels:
      app.kubernetes.io/name: istio-system
      helix.ai/component: service-mesh
  sourceRef:
    kind: GitRepository
    name: helix-ai
    namespace: flux-system
  path: ./IaC/kubernetes/apps/base/mesh/istio-system/app
