apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: mesh
  labels:
    app.kubernetes.io/name: istio-base
    app.kubernetes.io/instance: istio-base
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/part-of: helix-platform
    helix.ai/component: service-mesh-core
spec:
  interval: 30m
  timeout: 10m
  maxHistory: 5
  releaseName: istio-base
  targetNamespace: mesh
  chart:
    spec:
      chart: base
      version: "1.23.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    remediation:
      retries: 3
      enable: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: istio-base-values
      valuesKey: base.yaml
